BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button: #1
        text: 'Clear'
        font_size: 42
        on_release: app.clear_field()
    TextInput: #2
        id: input_name
        text: ''
        font_size: 42
    Button: #3
        text: 'Greet'
        font_size: 42
        on_press: app.handle_greet()
    Label: #4
        id: output_label
        text: 'Enter your name'
        font_size: 42
        color: (1, 1, 0, 1)